-- MySQL Script generated by MySQL Workbench
-- Sun Mar 22 00:50:14 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escola_financeiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola_financeiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola_financeiro` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`inadimplência`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inadimplência` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inadimplência` (
  `cod_inadimplencia` INT NOT NULL,
  `data_registro` DATE NULL DEFAULT NULL,
  `valor_original` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_inadimplencia`),
  UNIQUE INDEX `cod_inadimplencia_UNIQUE` (`cod_inadimplencia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contratos_educacionais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contratos_educacionais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contratos_educacionais` (
  `id_contrato` INT NULL DEFAULT NULL,
  `aluno_nome` VARCHAR(100) NULL DEFAULT NULL,
  `data_inicio` DATE NULL DEFAULT NULL,
  `data_fim` DATE NULL DEFAULT NULL,
  `valor_total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contrato`));


-- -----------------------------------------------------
-- Table `mydb`.`mensalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mensalidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mensalidades` (
  `id_mensalidade` INT NULL DEFAULT NULL,
  `id_contrato` INT NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_vencimento` DATE NULL DEFAULT NULL,
  `status` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_mensalidade`),
  INDEX (`id_contrato` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_contrato`)
    REFERENCES `mydb`.`contratos_educacionais` (`id_contrato`));


-- -----------------------------------------------------
-- Table `mydb`.`contas_receber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contas_receber` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contas_receber` (
  `id_conta_receber` INT NULL DEFAULT NULL,
  `id_mensalidade` INT NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_recebimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_conta_receber`),
  INDEX (`id_mensalidade` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_mensalidade`)
    REFERENCES `mydb`.`mensalidades` (`id_mensalidade`));


-- -----------------------------------------------------
-- Table `mydb`.`contas_pagar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contas_pagar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contas_pagar` (
  `id_conta_pagar` INT NULL DEFAULT NULL,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_conta_pagar`));


-- -----------------------------------------------------
-- Table `mydb`.`pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pagamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pagamentos` (
  `id_pagamento` INT NULL DEFAULT NULL,
  `id_conta_receber` INT NULL DEFAULT NULL,
  `valor_pago` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX (`id_conta_receber` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_conta_receber`)
    REFERENCES `mydb`.`contas_receber` (`id_conta_receber`));


-- -----------------------------------------------------
-- Table `mydb`.`inadimplencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inadimplencia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inadimplencia` (
  `cod_inadimplencia` INT NULL DEFAULT NULL,
  `id_mensalidade` INT NULL DEFAULT NULL,
  `data_registro` DATE NULL DEFAULT NULL,
  `valor_original` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_inadimplencia`),
  INDEX (`id_mensalidade` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_mensalidade`)
    REFERENCES `mydb`.`mensalidades` (`id_mensalidade`));

USE `escola_financeiro` ;

-- -----------------------------------------------------
-- Table `escola_financeiro`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Pessoa` (
  `CPF` CHAR(11) NOT NULL,
  `primeiro_nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `data_nasc` DATE NULL,
  `genero` ENUM("") NULL,
  `deficiencia` VARCHAR(45) NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`aluno` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`aluno` (
  `RA` INT NULL AUTO_INCREMENT,
  `CPF` CHAR(11) NOT NULL,
  `religiao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RA`),
  INDEX `fk_aluno_Pessoa1_idx` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_Pessoa1`
    FOREIGN KEY (`CPF`)
    REFERENCES `escola_financeiro`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `escola_financeiro`.`contratos_educacionais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`contratos_educacionais` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`contratos_educacionais` (
  `registro_nrcontrato` INT NULL AUTO_INCREMENT,
  `RA` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `status_contrato` ENUM('ativo', 'bloqueado', 'trancado') NULL,
  PRIMARY KEY (`registro_nrcontrato`),
  INDEX `fk_contratos_educacionais_aluno1_idx` (`RA` ASC) VISIBLE,
  CONSTRAINT `fk_contratos_educacionais_aluno1`
    FOREIGN KEY (`RA`)
    REFERENCES `escola_financeiro`.`aluno` (`RA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `escola_financeiro`.`mensalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`mensalidades` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`mensalidades` (
  `NSU` INT NULL AUTO_INCREMENT,
  `registro_nrcontrato` INT NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status_mensalidade` ENUM('pendente', 'pago', 'atrasado') NOT NULL,
  PRIMARY KEY (`NSU`),
  INDEX `fk_mensalidades_contratos_educacionais1_idx` (`registro_nrcontrato` ASC) VISIBLE,
  CONSTRAINT `fk_mensalidades_contratos_educacionais1`
    FOREIGN KEY (`registro_nrcontrato`)
    REFERENCES `escola_financeiro`.`contratos_educacionais` (`registro_nrcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `escola_financeiro`.`contas_receber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`contas_receber` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`contas_receber` (
  `id_conta_receber` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `NSU` INT NULL,
  `valor` DECIMAL(10,2) NULL,
  `data_prevista` DATE NULL DEFAULT NULL,
  `data_recebimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id_conta_receber`),
  INDEX (`NSU` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`NSU`)
    REFERENCES `escola_financeiro`.`mensalidades` (`NSU`));


-- -----------------------------------------------------
-- Table `escola_financeiro`.`pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`pagamentos` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`pagamentos` (
  `id_pagamento` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `id_conta_receber` INT NULL DEFAULT NULL,
  `valor_pago` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX (`id_conta_receber` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_conta_receber`)
    REFERENCES `escola_financeiro`.`contas_receber` (`id_conta_receber`));


-- -----------------------------------------------------
-- Table `escola_financeiro`.`inadimplencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`inadimplencia` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`inadimplencia` (
  `id_inadimplencia` INT NOT NULL AUTO_INCREMENT,
  `NSU` INT NOT NULL,
  `data_registro` DATE NULL DEFAULT NULL,
  `multa` DECIMAL(10,2) NULL DEFAULT NULL,
  `juros` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_inadimplencia`),
  INDEX `fk_inadimplencia_mensalidades1_idx` (`NSU` ASC) VISIBLE,
  CONSTRAINT `fk_inadimplencia_mensalidades1`
    FOREIGN KEY (`NSU`)
    REFERENCES `escola_financeiro`.`mensalidades` (`NSU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `escola_financeiro`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`fornecedor` (
  `id_fornecedor` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `cnpj` CHAR(14) NULL DEFAULT NULL,
  PRIMARY KEY (`id_fornecedor`));


-- -----------------------------------------------------
-- Table `escola_financeiro`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`funcionario` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`funcionario` (
  `id_funcionario` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  `cargo` VARCHAR(50) NULL DEFAULT NULL,
  `salario` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_funcionario`));


-- -----------------------------------------------------
-- Table `escola_financeiro`.`despesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`despesas` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`despesas` (
  `id_conta_pagar` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_vencimento` DATE NULL DEFAULT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  `id_fornecedor` INT NULL DEFAULT NULL,
  `id_funcionario` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_conta_pagar`),
  INDEX (`id_fornecedor` ASC) VISIBLE,
  INDEX (`id_funcionario` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_fornecedor`)
    REFERENCES `escola_financeiro`.`fornecedor` (`id_fornecedor`),
  CONSTRAINT ``
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `escola_financeiro`.`funcionario` (`id_funcionario`));


-- -----------------------------------------------------
-- Table `escola_financeiro`.`Fone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Fone` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Fone` (
  `telefone` INT NOT NULL,
  `DDD` ENUM("") NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`telefone`, `DDD`),
  INDEX `fk_Fone_Pessoa1_idx` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Fone_Pessoa1`
    FOREIGN KEY (`CPF`)
    REFERENCES `escola_financeiro`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`Contatos_Responsavel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Contatos_Responsavel` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Contatos_Responsavel` (
  `Fone_telefone` INT NOT NULL,
  `Fone_DDD` ENUM("11") NOT NULL,
  `email_responsavel` VARCHAR(45) NULL,
  INDEX `fk_Contatos_Responsavel_Fone1_idx` (`Fone_telefone` ASC, `Fone_DDD` ASC) VISIBLE,
  CONSTRAINT `fk_Contatos_Responsavel_Fone1`
    FOREIGN KEY (`Fone_telefone` , `Fone_DDD`)
    REFERENCES `escola_financeiro`.`Fone` (`telefone` , `DDD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
