-- MySQL Script generated by MySQL Workbench
-- Wed Apr  1 19:51:38 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema escola_financeiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola_financeiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola_financeiro` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `escola_financeiro`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Pessoa` (
  `CPF` CHAR(11) NOT NULL,
  `primeiro_nome` VARCHAR(45) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(45) NULL DEFAULT NULL,
  `data_nasc` DATE NULL DEFAULT NULL,
  `genero` ENUM("") NULL DEFAULT NULL,
  `deficiencia` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`aluno` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`aluno` (
  `RA` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `CPF` CHAR(11) NOT NULL,
  `religiao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RA`),
  INDEX `fk_aluno_Pessoa1_idx` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_Pessoa1`
    FOREIGN KEY (`CPF`)
    REFERENCES `escola_financeiro`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`contratos_educacionais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`contratos_educacionais` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`contratos_educacionais` (
  `registro_nrcontrato` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `RA` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `status_contrato` ENUM('ativo', 'bloqueado', 'trancado') NULL DEFAULT NULL,
  PRIMARY KEY (`registro_nrcontrato`),
  INDEX `fk_contratos_educacionais_aluno1_idx` (`RA` ASC) VISIBLE,
  CONSTRAINT `fk_contratos_educacionais_aluno1`
    FOREIGN KEY (`RA`)
    REFERENCES `escola_financeiro`.`aluno` (`RA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `escola_financeiro`.`mensalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`mensalidades` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`mensalidades` (
  `NSU` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `registro_nrcontrato` INT NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status_mensalidade` ENUM('pendente', 'pago', 'atrasado') NOT NULL,
  PRIMARY KEY (`NSU`),
  INDEX `fk_mensalidades_contratos_educacionais1_idx` (`registro_nrcontrato` ASC) VISIBLE,
  CONSTRAINT `fk_mensalidades_contratos_educacionais1`
    FOREIGN KEY (`registro_nrcontrato`)
    REFERENCES `escola_financeiro`.`contratos_educacionais` (`registro_nrcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`contas_receber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contas_receber` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contas_receber` (
  `id_conta_receber` INT NULL DEFAULT NULL,
  `NSU` INT NULL,
  `valor` DECIMAL(10,2) NULL,
  `data_prevista` DATE NULL,
  `data_recebimento` DATE NULL,
  PRIMARY KEY (`id_conta_receber`),
  INDEX `fk_contas_receber_mensalidades1_idx` (`NSU` ASC) VISIBLE,
  CONSTRAINT `fk_contas_receber_mensalidades1`
    FOREIGN KEY (`NSU`)
    REFERENCES `escola_financeiro`.`mensalidades` (`NSU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pagamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pagamentos` (
  `id_pagamento` INT NULL DEFAULT NULL,
  `id_conta_receber` INT NULL DEFAULT NULL,
  `valor_pago` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_pagamento` DATE NULL DEFAULT NULL,
  `forma_pagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX (`id_conta_receber` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_conta_receber`)
    REFERENCES `mydb`.`contas_receber` (`id_conta_receber`));

USE `escola_financeiro` ;

-- -----------------------------------------------------
-- Table `escola_financeiro`.`inadimplencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`inadimplencia` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`inadimplencia` (
  `id_inadimplencia` INT NOT NULL AUTO_INCREMENT,
  `NSU` INT NOT NULL,
  `data_registro` DATE NULL DEFAULT NULL,
  `multa` DECIMAL(10,2) NULL DEFAULT NULL,
  `juros` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_inadimplencia`),
  INDEX `fk_inadimplencia_mensalidades1_idx` (`NSU` ASC) VISIBLE,
  CONSTRAINT `fk_inadimplencia_mensalidades1`
    FOREIGN KEY (`NSU`)
    REFERENCES `escola_financeiro`.`mensalidades` (`NSU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `escola_financeiro`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`produto` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`produto` (
  `id_produto` VARCHAR(45) NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`fornecedor` (
  `CNPJ` VARCHAR(100) NOT NULL,
  `id_produto` VARCHAR(45) NOT NULL,
  `razao_social` CHAR(14) NOT NULL,
  `nome_fantasia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CNPJ`),
  INDEX `fk_fornecedor_produto1_idx` (`id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_fornecedor_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `escola_financeiro`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`folha_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`folha_pagamento` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`folha_pagamento` (
  `n_contratacao` INT NOT NULL,
  `salario` VARCHAR(45) NOT NULL,
  `descontos` VARCHAR(45) NULL DEFAULT NULL,
  `data_pagamento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`n_contratacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`despesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`despesas` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`despesas` (
  `conta_pendente` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `salario` INT NOT NULL,
  `tipo_despesa` ENUM('servico', 'compra') NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`conta_pendente`),
  INDEX `fk_despesas_escola_salarios_pagar1_idx` (`salario` ASC) VISIBLE,
  CONSTRAINT `fk_despesas_escola_salarios_pagar1`
    FOREIGN KEY (`salario`)
    REFERENCES `escola_financeiro`.`folha_pagamento` (`n_contratacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`Fone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Fone` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Fone` (
  `telefone` INT NOT NULL,
  `DDD` ENUM("") NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`telefone`, `DDD`),
  INDEX `fk_Fone_Pessoa1_idx` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Fone_Pessoa1`
    FOREIGN KEY (`CPF`)
    REFERENCES `escola_financeiro`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`Contatos_Responsavel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Contatos_Responsavel` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Contatos_Responsavel` (
  `email_responsavel` VARCHAR(45) NOT NULL,
  `Fone_telefone` INT NOT NULL,
  `Fone_DDD` ENUM("11") NOT NULL,
  `RA` INT NOT NULL,
  INDEX `fk_Contatos_Responsavel_Fone1_idx` (`Fone_telefone` ASC, `Fone_DDD` ASC) VISIBLE,
  INDEX `fk_Contatos_Responsavel_aluno1_idx` (`RA` ASC) VISIBLE,
  CONSTRAINT `fk_Contatos_Responsavel_Fone1`
    FOREIGN KEY (`Fone_telefone` , `Fone_DDD`)
    REFERENCES `escola_financeiro`.`Fone` (`telefone` , `DDD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contatos_Responsavel_aluno1`
    FOREIGN KEY (`RA`)
    REFERENCES `escola_financeiro`.`aluno` (`RA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`desc_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`desc_compra` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`desc_compra` (
  `desc_compra` INT NOT NULL,
  `CNPJ` VARCHAR(100) NOT NULL,
  `tipo_compra` ENUM('limpeza', 'alimento', 'material') NULL DEFAULT NULL,
  PRIMARY KEY (`desc_compra`),
  INDEX `fk_desc_compra_fornecedor1_idx` (`CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_desc_compra_fornecedor1`
    FOREIGN KEY (`CNPJ`)
    REFERENCES `escola_financeiro`.`fornecedor` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`compras` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`compras` (
  `id_compra` INT NOT NULL,
  `conta_pendente` INT NOT NULL,
  `desc_compra` INT NOT NULL,
  `qtd_item` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `fk_compras_despesas1_idx` (`conta_pendente` ASC) VISIBLE,
  INDEX `fk_compras_desc_compra1_idx` (`desc_compra` ASC) VISIBLE,
  CONSTRAINT `fk_compras_despesas1`
    FOREIGN KEY (`conta_pendente`)
    REFERENCES `escola_financeiro`.`despesas` (`conta_pendente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_desc_compra1`
    FOREIGN KEY (`desc_compra`)
    REFERENCES `escola_financeiro`.`desc_compra` (`desc_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`desc_servico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`desc_servico` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`desc_servico` (
  `desc_servico` VARCHAR(45) NOT NULL,
  `tipo_servico` ENUM('infraestrutura', 'manutencao', 'palestras') NULL DEFAULT NULL,
  PRIMARY KEY (`desc_servico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`servicos` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`servicos` (
  `id.servicos` INT NOT NULL,
  `conta_pendente` INT NOT NULL,
  `desc_servico` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id.servicos`),
  INDEX `fk_servicos_despesas1_idx` (`conta_pendente` ASC) VISIBLE,
  INDEX `fk_servicos_desc_servico1_idx` (`desc_servico` ASC) VISIBLE,
  CONSTRAINT `fk_servicos_despesas1`
    FOREIGN KEY (`conta_pendente`)
    REFERENCES `escola_financeiro`.`despesas` (`conta_pendente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_desc_servico1`
    FOREIGN KEY (`desc_servico`)
    REFERENCES `escola_financeiro`.`desc_servico` (`desc_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
