-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 23:09:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema escola_financeiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escola_financeiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola_financeiro` ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `escola_financeiro`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Pessoa` (
  `CPF` CHAR(11) NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `genero` ENUM("") NOT NULL,
  `deficiencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`aluno` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`aluno` (
  `RA` INT NOT NULL AUTO_INCREMENT,
  `CPF` CHAR(11) NOT NULL,
  `religiao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`RA`),
  INDEX `fk_aluno_Pessoa1_idx` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_aluno_Pessoa1`
    FOREIGN KEY (`CPF`)
    REFERENCES `escola_financeiro`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`contratos_educacionais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`contratos_educacionais` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`contratos_educacionais` (
  `registro_nrcontrato` INT NOT NULL AUTO_INCREMENT,
  `RA` INT NOT NULL,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  `status_contrato` ENUM('ativo', 'bloqueado', 'trancado') NOT NULL DEFAULT 'Ativo',
  PRIMARY KEY (`registro_nrcontrato`),
  INDEX `fk_contratos_educacionais_aluno1_idx` (`RA` ASC) VISIBLE,
  CONSTRAINT `fk_contratos_educacionais_aluno1`
    FOREIGN KEY (`RA`)
    REFERENCES `escola_financeiro`.`aluno` (`RA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `escola_financeiro`.`mensalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`mensalidades` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`mensalidades` (
  `NSU` INT NOT NULL AUTO_INCREMENT,
  `registro_nrcontrato` INT NOT NULL,
  `data_emissao` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status_mensalidade` ENUM('pendente', 'pago', 'atrasado') NOT NULL DEFAULT 'pendente',
  PRIMARY KEY (`NSU`),
  INDEX `fk_mensalidades_contratos_educacionais1_idx` (`registro_nrcontrato` ASC) VISIBLE,
  UNIQUE INDEX `NSU_UNIQUE` (`NSU` ASC) VISIBLE,
  CONSTRAINT `fk_mensalidades_contratos_educacionais1`
    FOREIGN KEY (`registro_nrcontrato`)
    REFERENCES `escola_financeiro`.`contratos_educacionais` (`registro_nrcontrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`contas_receber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contas_receber` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contas_receber` (
  `id_conta_receber` INT NOT NULL,
  `NSU` INT NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_prevista` DATE NOT NULL,
  `data_recebimento` DATE NULL,
  PRIMARY KEY (`id_conta_receber`),
  INDEX `fk_contas_receber_mensalidades1_idx` (`NSU` ASC) VISIBLE,
  UNIQUE INDEX `NSU_UNIQUE` (`NSU` ASC) VISIBLE,
  CONSTRAINT `fk_contas_receber_mensalidades1`
    FOREIGN KEY (`NSU`)
    REFERENCES `escola_financeiro`.`mensalidades` (`NSU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pagamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pagamentos` (
  `id_pagamento` INT NOT NULL,
  `id_conta_receber` INT NOT NULL,
  `valor_pago` DECIMAL(10,2) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `forma_pagamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pagamento`),
  INDEX (`id_conta_receber` ASC) VISIBLE,
  CONSTRAINT ``
    FOREIGN KEY (`id_conta_receber`)
    REFERENCES `mydb`.`contas_receber` (`id_conta_receber`));

USE `escola_financeiro` ;

-- -----------------------------------------------------
-- Table `escola_financeiro`.`inadimplencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`inadimplencia` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`inadimplencia` (
  `id_inadimplencia` INT NOT NULL AUTO_INCREMENT,
  `NSU` INT NOT NULL,
  `data_registro` DATE NOT NULL,
  `multa` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `juros` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  PRIMARY KEY (`id_inadimplencia`),
  INDEX `fk_inadimplencia_mensalidades1_idx` (`NSU` ASC) VISIBLE,
  UNIQUE INDEX `NSU_UNIQUE` (`NSU` ASC) VISIBLE,
  CONSTRAINT `fk_inadimplencia_mensalidades1`
    FOREIGN KEY (`NSU`)
    REFERENCES `escola_financeiro`.`mensalidades` (`NSU`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `escola_financeiro`.`produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`produto` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`produto` (
  `id_produto` VARCHAR(45) NOT NULL,
  `nome_produto` VARCHAR(45) NOT NULL,
  `valor_base` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`fornecedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`fornecedor` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`fornecedor` (
  `CNPJ` VARCHAR(14) NOT NULL,
  `razao_social` CHAR(14) NOT NULL,
  `nome_fantasia` VARCHAR(45) NOT NULL,
  `contato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CNPJ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`compras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`compras` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`compras` (
  `NFe` CHAR(44) NOT NULL,
  `Fk_CNPJ` VARCHAR(14) NOT NULL,
  `valorT_nota` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`NFe`),
  INDEX `fk_compras_fornecedor1_idx` (`Fk_CNPJ` ASC) VISIBLE,
  CONSTRAINT `fk_compras_fornecedor1`
    FOREIGN KEY (`Fk_CNPJ`)
    REFERENCES `escola_financeiro`.`fornecedor` (`CNPJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`servicos` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`servicos` (
  `id_servicos` INT NOT NULL AUTO_INCREMENT,
  `desc_servico` VARCHAR(45) NOT NULL,
  `valor_servico` DECIMAL(10,2) NOT NULL,
  `cpf_prestador` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_servicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`contas_pagar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`contas_pagar` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`contas_pagar` (
  `cod_despesa` INT NOT NULL AUTO_INCREMENT,
  `NFe` CHAR(44) NOT NULL,
  `id_servicos` INT NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`cod_despesa`, `NFe`),
  INDEX `fk_contas_pagar_compras1_idx` (`NFe` ASC) VISIBLE,
  INDEX `fk_contas_pagar_servicos1_idx` (`id_servicos` ASC) VISIBLE,
  CONSTRAINT `fk_contas_pagar_compras1`
    FOREIGN KEY (`NFe`)
    REFERENCES `escola_financeiro`.`compras` (`NFe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contas_pagar_servicos1`
    FOREIGN KEY (`id_servicos`)
    REFERENCES `escola_financeiro`.`servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`Fone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Fone` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Fone` (
  `telefone` INT NOT NULL,
  `DDD` ENUM("") NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  PRIMARY KEY (`telefone`, `DDD`),
  INDEX `fk_Fone_Pessoa1_idx` (`CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Fone_Pessoa1`
    FOREIGN KEY (`CPF`)
    REFERENCES `escola_financeiro`.`Pessoa` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`Contatos_Responsavel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`Contatos_Responsavel` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`Contatos_Responsavel` (
  `email_responsavel` VARCHAR(45) NOT NULL,
  `Fone_telefone` INT NOT NULL,
  `Fone_DDD` ENUM("11") NOT NULL,
  `RA` INT NOT NULL,
  INDEX `fk_Contatos_Responsavel_Fone1_idx` (`Fone_telefone` ASC, `Fone_DDD` ASC) VISIBLE,
  INDEX `fk_Contatos_Responsavel_aluno1_idx` (`RA` ASC) VISIBLE,
  CONSTRAINT `fk_Contatos_Responsavel_Fone1`
    FOREIGN KEY (`Fone_telefone` , `Fone_DDD`)
    REFERENCES `escola_financeiro`.`Fone` (`telefone` , `DDD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Contatos_Responsavel_aluno1`
    FOREIGN KEY (`RA`)
    REFERENCES `escola_financeiro`.`aluno` (`RA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola_financeiro`.`itens_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola_financeiro`.`itens_compra` ;

CREATE TABLE IF NOT EXISTS `escola_financeiro`.`itens_compra` (
  `id_item` VARCHAR(45) NOT NULL,
  `NFe` CHAR(44) NOT NULL,
  `id_produto` VARCHAR(45) NOT NULL,
  `qtd` INT NOT NULL,
  `valor_item` DECIMAL(10,2) NOT NULL,
  INDEX `fk_itens_compra_compras1_idx` (`NFe` ASC) VISIBLE,
  INDEX `fk_itens_compra_produto1_idx` (`id_produto` ASC) VISIBLE,
  PRIMARY KEY (`id_item`),
  CONSTRAINT `fk_itens_compra_compras1`
    FOREIGN KEY (`NFe`)
    REFERENCES `escola_financeiro`.`compras` (`NFe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_compra_produto1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `escola_financeiro`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
