-- MySQL Script generated by MySQL Workbench
-- Thu Mar 19 19:48:15 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`contratos_educacionais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contratos_educacionais` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contratos_educacionais` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mensalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`mensalidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`mensalidades` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contas_receber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contas_receber` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contas_receber` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contas_pagar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contas_pagar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contas_pagar` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pagamentos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pagamentos` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inadimplência`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`inadimplência` ;

CREATE TABLE IF NOT EXISTS `mydb`.`inadimplência` (
  `cod_inadimplencia` INT NOT NULL,
  `data_registro` DATE NULL,
  `valor_original` DECIMAL(10,2) NULL,
  PRIMARY KEY (`cod_inadimplencia`),
  UNIQUE INDEX `cod_inadimplencia_UNIQUE` (`cod_inadimplencia` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
